version: "3.8"

services:
  app:
    build: .
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/glovo
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=230218
      - SPRING_JPA_HIBERNATE_DDL_AUTO=create
    depends_on:
      - db
    command: bash -c "alembic upgrade head && uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload"

  db:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=glovo
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=230218